version: "3.8"

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - kafka_data:/var/lib/kafka/data
  cdc-gateway:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: cdc-gateway
    depends_on:
      - kafka
    environment:
      CDC_GATEWAY_CONFIG: /config/config.yaml
      CDC_GATEWAY_GRPC_ADDR: ":9090"

      KAFKA_BROKERS: "kafka:9092"
      KAFKA_INPUT_TOPIC: "dbserver1.inventory.customers"
      KAFKA_CONSUMER_GROUP: "cdc-gateway-dev"

    volumes:
      - ../config.yaml:/config/config.yaml:ro

    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped
  ## For Running go scripts inside conatiner
  # cdc-dev:
  #   build:
  #     context: ..
  #     dockerfile: Dockerfile.dev
  #   container_name: cdc-dev
  #   depends_on:
  #     - kafka
  #   environment:
  #     CDC_GATEWAY_CONFIG: /config/config.yaml
  #     CDC_GATEWAY_GRPC_ADDR: ":9090"
  #   volumes:
  #     - ../config.yaml:/config/config.yaml:ro

  #   stdin_open: true
  #   tty: true


volumes:
  kafka_data:
